config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:show, :create, :new]
  resources :users, only: [:create, :edit, :show, :update]

  # 2 options for votes routes
    #1 resources :votes, only: [:create]
    #2 POST /posts/:id/vote => PostsController#vote
    #  POST /comments/:id/vote => CommentsController#vote
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: "User"
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(comment_params)
    # @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.creator = current_user
    # @comment.post = @post

    if @comment.save
      flash[:notice] = "Your comment was added"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    require_user
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "You can only vote on a comment once"
        end
        redirect_to :back
      end
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<% show_comment ||= false %>
<div class="row">
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br />
      <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
      <br />
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% else %>
      <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
      <br />
    <% end %>
  </div>
  <div class="well row span8">
    <em>"<%= comment.body %>"</em>
    <% if show_comment %>
      on <%= link_to comment.comment.title, comment_path(comment.comment) %>
    <% else %>
      <span class="quiet">commented by </span><%= link_to comment.creator.username, user_path(comment.creator) %>
    <% end %>
    <small> at <%= display_datetime comment.created_at %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes")
<% else %>
  alert("You can only vote once on a comment")
  // let a = $("a").addClass("close").attr("data-dismiss", "alert").text("&#215;")
  // let div = $("div").addClass("alert alert-error").append()
  // $("#ajax_message")
<% end %>