config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:show, :create, :new]
  resources :users, only: [:create, :edit, :show, :update]

  # 2 options for votes routes
    #1 resources :votes, only: [:create]
    #2 POST /posts/:id/vote => PostsController#vote
    #  POST /comments/:id/vote => CommentsController#vote
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: "User"
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  after_validation :generate_slug

  validates :url, presence: true, uniqueness: true
  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]
  # 1. Set up instance variable for action
  # 2. redirect based on some condition (logged in)

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
    @categories = Category.all
    # renders new view with form partial
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    if @post.save
      flash[:notice] = "Your post was created"
      redirect_to posts_path
    else
      render :new # uses form partial
    end
  end

  def edit
    # renders edit view with form partial
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path(@post)
    else
      render :edit # uses form partial
    end
  end

  def vote
    require_user
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:error] = "You can only vote for on a post once"
        end
        redirect_to :back
        #redirect_to :back, notice: "Your vote was counted"
      end
      format.js  #do# By default tries to render js template with same name as action
      #   if @vote.valid?
      #     flash.now[:notice] = 'Your vote was counted'
      #   else
      #     flash.now[:error] = "You cant do that"
      #   end
      # end
    end
  end

  private

  def post_params # mass assigning post parameters strong parameters
    # if user.admin?
      params.require(:post).permit(:title, :url, :description, category_ids: [])#!
    # else
      # params.require(:post).permit(:title, :url)
    # end
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end

end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class="control-group">
      <% f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>

    </div>

    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br />
      <span id="post_<%= post.id %>_votes"><%= post.total_votes %> votes</span>
      <br />
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% else %>
      <%= post.total_votes %> votes
      <br />
    <% end %>
  </div>
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p>
      <span class='quiet'>posted by </span><%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= display_datetime post.created_at %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All of THE Posts' %>
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>



<!-- <ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul> -->

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new Post' %>

<!-- <div class="well"> -->
  <%= render 'form' %>
<!-- </div> -->

app/views/posts/show.html.erb
<% if logged_in? && @post.creator.id == current_user.id %>
  <p class="pull-right">
    [<%= link_to("Edit Post", edit_post_path(@post)) %>]
  </p>
<% end %>
<p>
  <%= render @post.categories %>
</p>
<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr></hr>

<%= link_to 'go back to all posts', posts_path %>
<br><br />
<% if logged_in? %>
  <%= render 'shared/errors', obj: @comment %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.label :body, 'Leave a Comment' %>
    <%= f.text_area :body, rows: 3, class: 'span4' %>
    <br />
    <%= f.submit "Create Comment", class: 'btn btn-primary' %>
  <% end %>
<% end %>

<div class="comments">
  <h4>Comments</h4>
  <% if @post.comments.empty? %>
    <div class="well row span8">
      <p>No comments yet</p>
    </div>
  <% else %>
    <% @post.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% end %>
</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.id %>_votes").html("<%= @post.total_votes %> votes")
<% else %>
  alert("You can only vote once on a post")
  // let a = $("a").addClass("close").attr("data-dismiss", "alert").text("&#215;")
  // let div = $("div").addClass("alert alert-error").append()
  // $("#ajax_message")
<% end %>